### ISSUE TITLE
White page with Less Compiler

### ISSUE THREAD

**Issue by sorgina** [ndeet/plg_system_less#29]
Hello,

Excuse my English, I use Google Translate to write to you

I use the template Helix3 with Joomla 3.4.3. I use LESS 0.8.0 Compiler for compiling a file custom.less custom.css.
To learn how to use LESS, I created a test page with only .foo {color: red;}.
The display of the site frontend produces a blank page.
If I disable LESS compile, everything returns to normal. I tried with all versions of LESSC  with the same result.

Lomart (the french translator of LESS Compiler) tried to help me without finding solution.

Best regards

**Comment by ndeet** [comment]
Hi,

does it happen only with the mentioned Helix3 Template? If yes, they do something in the code which breaks the less compiler (maybe they load there own without checking if there is already one loaded). Maybe their support forum is then the better place to ask.

If not, let me see the error and I will try to help you.

Here is a good introduction on ways to see the actual error message instead of the white screen:
https://www.ostraining.com/blog/joomla/white-screen-of-death/

**Comment by sorgina** [comment]
Hi

Thank you for your help. Actually it comes from Helix. I tried with 
Beez3 and Protostar and I have more white page. I'll go ask on their 
forum. FYI I put you attached a copy of the error message screen.

**Comment by ndeet** [comment]
Hi @sorgina glad you figured it out. I don't see any attachment though.

**Comment by ndeet** [comment]
Closing as the issue seems to be resolved.
