### ISSUE TITLE
Autoprefixer capabilities

### ISSUE THREAD

**Issue by Olg-E** [ndeet/plg_system_less#33]
Hi Andreas,
Do you plan add Autoprefixer capabilities (https://github.com/postcss/autoprefixer, https://github.com/less/less-plugin-autoprefix) to you plugin?

**Comment by ndeet** [comment]
Hi Olg-E,

generally autoprefixing is a good idea and a very nice feature. The thing is, these are JS libraries where you need nodeJS tooling with Grunt/Gulp/Webpack/... build tools. plg_system_less uses a [PHP implementation](https://github.com/leafo/lessphp) of the original JS [lessc](http://lesscss.org/) library. So to make autoprefixer work someone would need to port it to PHP too. 

To be honest, since I wrote the plugin a lot has changed in frontend development. At that time that may have made sense to compile Less with PHP for small changes (but no, in hindsight it may never had made sense :)).
  
If you want features like autoprefixing and many other nice things like minification, JS bundling, live reload, ... you should look into how to run those tools with nodeJS and Gulp. Maybe also switch from Less to Sass (Now with twitter bootsrap switching from Less to Sass I guess Less will gone in next 1-2 years).

**Comment by ndeet** [comment]
Closing, thx.
